version: '3.8'

services:
  web:
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A app.celery_utils:celery worker --loglevel=info #updated
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: "redis:alpine"